@{
    RootModule        = 'Pmc.Strict.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = '5b2d6a0a-8a8f-4e2a-9d0d-3a3b0e2a3b6f'
    Author            = 'pmc'
    CompanyName       = 'pmc'
    Copyright         = '(c) pmc'
    Description       = 'Strict, homogeneous domain-action command engine for pmc.'
    PowerShellVersion = '5.1'
    TypesToProcess    = @()
    FunctionsToExport = @(
        'Invoke-PmcCommand',
        'Initialize-PmcEnhancedCommandProcessor',
        'Get-PmcEnhancedCommandProcessor',
        'Invoke-PmcEnhancedCommand',
        'Get-PmcSchema',
        'Get-PmcHelp',
        'Get-PmcHelpData',
        'Show-PmcHelpUI',
        'Show-PmcHelpDomain',
        'Show-PmcHelpCommand',
        'Show-PmcHelpQuery',
        'Show-PmcHelpAll',
        'Start-PmcProjectWizard',
        'Set-PmcConfigProvider',
        'Enable-PmcInteractiveMode',
        'Disable-PmcInteractiveMode',
        'Get-PmcInteractiveStatus',
        'Read-PmcCommand',
        'Write-PmcDebug',
        'Get-PmcDebugStatus',
        'Show-PmcDebugLog',
        'Measure-PmcOperation',
        'Initialize-PmcDebugSystem',
        'Initialize-PmcSecuritySystem',
        'Initialize-PmcThemeSystem',
        'Update-PmcDebugFromConfig',
        'Update-PmcSecurityFromConfig',
        'Get-PmcConfig',
        'Save-PmcConfig',
        'Get-PmcConfigProviders',
        'Set-PmcConfigProviders',
        'Get-PmcState',
        'Set-PmcState',
        'ConvertTo-PmcTokens',
        'ConvertTo-PmcDate',
        'Show-PmcSmartHelp',
        'Write-PmcStyled',
        'Get-PmcStyle',
        'Get-PmcColorPalette',
        'Get-PmcColorSequence',
        'ConvertFrom-PmcHex',
        'Test-PmcInputSafety',
        'Test-PmcPathSafety',
        'Invoke-PmcSecureFileOperation',
        'Protect-PmcUserInput',
        'Get-PmcSecurityStatus',
        'Set-PmcSecurityLevel',
        # TASK DOMAIN HANDLERS
        'Add-PmcTask',
        'Get-PmcTaskList',
        'Show-PmcTask',
        'Set-PmcTask',
        'Complete-PmcTask',
        'Remove-PmcTask',
        'Move-PmcTask',
        'Set-PmcTaskPostponed',
        'Copy-PmcTask',
        'Add-PmcTaskNote',
        'Edit-PmcTask',
        'Find-PmcTask',
        'Set-PmcTaskPriority',
        'Show-PmcAgenda',
        'Show-PmcWeekTasks',
        'Show-PmcMonthTasks',
        # PROJECT DOMAIN HANDLERS
        'Invoke-PmcCreateProjectCore',
        'Add-PmcProject',
        'Get-PmcProjectList',
        'Show-PmcProject',
        'Set-PmcProject',
        'Rename-PmcProject',
        'Remove-PmcProject',
        'Set-PmcProjectArchived',
        'Set-PmcProjectFields',
        'Show-PmcProjectFields',
        'Get-PmcProjectStats',
        'Show-PmcProjectInfo',
        'Get-PmcRecentProjects',
        # TIME/TIMER DOMAIN HANDLERS
        'Add-PmcTimeEntry',
        'Get-PmcTimeReport',
        'Get-PmcTimeList',
        'Edit-PmcTimeEntry',
        'Remove-PmcTimeEntry',
        'Start-PmcTimer',
        'Stop-PmcTimer',
        'Get-PmcTimerStatus',
        # ACTIVITY DOMAIN
        'Get-PmcActivityList',
        # TEMPLATE DOMAIN
        'Save-PmcTemplate',
        'Invoke-PmcTemplate',
        'Get-PmcTemplateList',
        'Remove-PmcTemplate',
        # RECURRING DOMAIN
        'Add-PmcRecurringTask',
        # ALIAS DOMAIN
        'Add-PmcAlias',
        'Remove-PmcAlias',
        # DEPENDENCY DOMAIN
        'Add-PmcDependency',
        'Remove-PmcDependency',
        'Show-PmcDependencies',
        'Show-PmcDependencyGraph',
        # FOCUS DOMAIN
        'Set-PmcFocus',
        'Clear-PmcFocus',
        'Get-PmcFocusStatus',
        # SYSTEM DOMAIN
        'Invoke-PmcUndo',
        'Invoke-PmcRedo',
        'New-PmcBackup',
        'Clear-PmcCompletedTasks',
        # VIEW DOMAIN
        'Show-PmcTodayTasks',
        'Show-PmcTomorrowTasks',
        'Show-PmcOverdueTasks',
        'Show-PmcUpcomingTasks',
        'Show-PmcBlockedTasks',
        'Show-PmcNoDueDateTasks',
        'Show-PmcProjectsView',
        'Show-PmcNextTasks',
        # EXCEL DOMAIN
        'Import-PmcExcelData',
        'Show-PmcExcelPreview',
        'Get-PmcLatestExcelFile',
        # THEME DOMAIN
        'Reset-PmcTheme',
        'Edit-PmcTheme',
        'Get-PmcThemeList',
        'Apply-PmcTheme',
        'Show-PmcThemeInfo',
        # CONFIG DOMAIN
        'Show-PmcConfig',
        'Edit-PmcConfig',
        'Set-PmcConfigValue',
        'Reload-PmcConfig',
        'Validate-PmcConfig',
        'Set-PmcIconMode',
        # IMPORT/EXPORT DOMAIN
        'Import-PmcTasks',
        'Export-PmcTasks',
        # SHOW DOMAIN
        'Get-PmcAliasList',
        'Show-PmcCommands',
        # HELP DOMAIN
        'Show-PmcCommandBrowser',
        'Show-PmcHelpExamples',
        'Show-PmcHelpGuide',
        # SHORTCUT-ONLY FUNCTIONS
        'Get-PmcStats',
        'Show-PmcBurndown',
        'Get-PmcVelocity',
        'Set-PmcTheme',
        'Show-PmcPreferences',
        'Invoke-PmcShortcutNumber',
        'Start-PmcReview',
        # XFLOW (Excel flow lite)
        'Set-PmcXFlowSourcePathInteractive',
        'Set-PmcXFlowDestPathInteractive',
        'Show-PmcXFlowPreview',
        'Invoke-PmcXFlowRun',
        'Export-PmcXFlowText',
        'Import-PmcXFlowMappingsFromFile',
        'Set-PmcXFlowLatestFromFile',
        'Show-PmcXFlowConfig',
        # CONSOLE UI
        'Start-PmcConsoleUI',
        # DATA DISPLAY SYSTEM
        'Show-PmcDataGrid',
        # UNIVERSAL DISPLAY SYSTEM
        'Show-PmcData',
        'Get-PmcDefaultColumns',
        'Register-PmcUniversalCommands',
        'Get-PmcUniversalCommands',
        'Ensure-PmcUniversalDisplay',
        # Interactive view entrypoints
        'Show-PmcTodayTasksInteractive',
        'Show-PmcOverdueTasksInteractive',
        'Show-PmcAgendaInteractive',
        'Show-PmcProjectsInteractive',
        'Show-PmcAllTasksInteractive',
        # QUERY DOMAIN
        'Invoke-PmcQuery',
        'Invoke-PmcEnhancedQuery',
        'Get-PmcQueryPerformanceStats',
        'Initialize-PmcEnhancedQueryEngine',
        'Evaluate-PmcQuery',
        'Get-PmcComputedRegistry',
        'Get-PmcQueryAlias',
        'Set-PmcQueryAlias',
        'Show-PmcCustomGrid',
        # SCREEN MANAGEMENT SYSTEM
        'Initialize-PmcScreen',
        'Clear-PmcContentArea',
        'Get-PmcContentBounds',
        'Set-PmcHeader',
        'Set-PmcInputPrompt',
        'Hide-PmcCursor',
        'Show-PmcCursor',
        'Reset-PmcScreen',
        'Write-PmcAtPosition',
        # DATA ACCESS
        'Get-PmcAllData',
        'Get-PmcDataProvider'
    )
    AliasesToExport   = @()
    CmdletsToExport   = @()
    VariablesToExport = @('PmcCommandMap', 'PmcShortcutMap', 'PmcCommandMeta')
}
